import { IPAsset } from './types';

export const INITIAL_ASSETS: IPAsset[] = [
  {
    id: 'IPA-1001',
    assetName: 'UNIQ MagSafe ShockProof Bumper Structure',
    ipType: 'Patent',
    brand: 'UNIQ',
    applicationNumber: 'SG-PAT-2023-08914',
    country: 'Singapore',
    countryCode: 'SG',
    filingDate: '2023-04-12',
    classes: 'IPC: H04M 1/02, H01F 38/14',
    registrationNumber: '10202308914Q',
    registrationDate: '2023-10-18',
    renewalDueDate: '2027-04-12',
    firmAgent: 'Allen & Gledhill LLP',
    applicant: 'Uniq Creation Pte. Ltd.',
    status: 'Registered',
    notes: 'Utility patent for shock-dispersing corner ribbing and flush magnetic alignment system for mobile phone protective cases.',
    documentName: 'patent_spec_sg_magproof.pdf',
    documentType: 'application/pdf',
    documentSize: '1.4 MB',
    createdAt: '2023-04-12T08:30:00Z',
    updatedAt: '2024-02-15T11:00:00Z',
  },
  {
    id: 'IPA-1002',
    assetName: 'UNIQ Wordmark & Monogram Logo',
    ipType: 'Trademark',
    brand: 'UNIQ',
    applicationNumber: 'US-TM-97841209',
    country: 'United States',
    countryCode: 'US',
    filingDate: '2022-09-18',
    classes: 'Class 9, 18',
    registrationNumber: '6894120',
    registrationDate: '2023-03-21',
    renewalDueDate: '2032-09-18',
    firmAgent: 'Sughrue Mion PLLC',
    applicant: 'Uniq Creation Pte. Ltd.',
    status: 'Registered',
    notes: 'Class 9 (Consumer electronic accessories, charging stations, phone cases, cable organizers) and Class 18 (Bags and laptop sleeves).',
    documentName: 'trademark_cert_us_uniq.pdf',
    documentType: 'application/pdf',
    documentSize: '820 KB',
    createdAt: '2022-09-18T04:15:00Z',
    updatedAt: '2023-01-20T09:00:00Z',
  },
  {
    id: 'IPA-1003',
    assetName: 'SKINARMA Streetwear Cybernetic Case Aesthetic',
    ipType: 'Design',
    brand: 'Skinarma',
    applicationNumber: 'JP-DES-2023-014522',
    country: 'Japan',
    countryCode: 'JP',
    filingDate: '2023-06-05',
    classes: 'Locarno: 14-03',
    registrationNumber: '-',
    registrationDate: '-',
    renewalDueDate: '2026-11-01',
    firmAgent: 'Seiwa Patent & Law',
    applicant: 'Skinarma Holdings Ltd.',
    status: 'Refusal Responded',
    notes: 'Registered industrial design for 3D layered topography and holographic strap module on tactical casing. Office action response filed.',
    documentName: 'design_reg_jp_skinarma.pdf',
    documentType: 'application/pdf',
    documentSize: '2.1 MB',
    createdAt: '2023-06-05T10:00:00Z',
    updatedAt: '2026-08-01T14:30:00Z',
  },
  {
    id: 'IPA-1004',
    assetName: 'SKINARMA Brand Trademark & Stylized Katakana',
    ipType: 'Trademark',
    brand: 'Skinarma',
    applicationNumber: 'KR-TM-402023019882',
    country: 'South Korea',
    countryCode: 'KR',
    filingDate: '2023-11-20',
    classes: 'Class 9, 14, 18',
    registrationNumber: '40-1988241',
    registrationDate: '2024-04-15',
    renewalDueDate: '2033-11-20',
    firmAgent: 'Kim & Chang',
    applicant: 'Skinarma Holdings Ltd.',
    status: 'Registered',
    notes: 'Trademark protection under Nice Classes 9, 14 (watch straps), and 18 for high-fashion technical accessories.',
    documentName: 'korean_tm_grant_skinarma.pdf',
    documentType: 'application/pdf',
    documentSize: '950 KB',
    createdAt: '2023-11-20T06:00:00Z',
    updatedAt: '2024-05-10T12:00:00Z',
  },
  {
    id: 'IPA-1005',
    assetName: 'ENERGEA MagDisc Dual-Coil Fast Wireless Charger',
    ipType: 'Patent',
    brand: 'Energea',
    applicationNumber: 'CN-PAT-202410382914',
    country: 'China',
    countryCode: 'CN',
    filingDate: '2024-03-15',
    classes: 'IPC: H02J 7/00, H02J 50/10',
    registrationNumber: '-',
    registrationDate: '-',
    renewalDueDate: '2028-03-15',
    firmAgent: 'Liu, Shen & Associates',
    applicant: 'Energea Tech Pte. Ltd.',
    status: 'Pending Examination',
    notes: 'Dual-axis thermal dissipation chamber with active inductive auto-centering protocol for 15W Qi2 rapid charging. Under technical examination.',
    documentName: 'cn_patent_filing_dossier.pdf',
    documentType: 'application/pdf',
    documentSize: '3.4 MB',
    createdAt: '2024-03-15T02:00:00Z',
    updatedAt: '2024-07-22T08:15:00Z',
  },
  {
    id: 'IPA-1006',
    assetName: 'ENERGEA Wordmark & Lightning Bolt Device',
    ipType: 'Trademark',
    brand: 'Energea',
    applicationNumber: 'UK-TM-003891720',
    country: 'United Kingdom',
    countryCode: 'GB',
    filingDate: '2021-08-10',
    classes: 'Class 9',
    registrationNumber: '-',
    registrationDate: '-',
    renewalDueDate: '2026-10-15',
    firmAgent: 'Boult Wade Tennant LLP',
    applicant: 'Energea Tech Pte. Ltd.',
    status: 'Refusal',
    notes: 'Class 9 (Power banks, GaN chargers, braided cables). Provisional refusal issued on relative grounds; legal counsel preparing opposition defense.',
    documentName: 'uk_ipo_reg_energea.pdf',
    documentType: 'application/pdf',
    documentSize: '650 KB',
    createdAt: '2021-08-10T11:45:00Z',
    updatedAt: '2026-08-15T16:00:00Z',
  },
  {
    id: 'IPA-1007',
    assetName: 'UNIQ Clarion Antimicrobial Clear Shield Housing',
    ipType: 'Design',
    brand: 'UNIQ',
    applicationNumber: 'EU-RCD-008923411',
    country: 'Germany',
    countryCode: 'DE',
    filingDate: '2022-01-14',
    classes: 'Locarno: 14-03, 03-01',
    registrationNumber: '008923411-0001',
    registrationDate: '2022-03-02',
    renewalDueDate: '2027-01-14',
    firmAgent: 'Vossius & Partner',
    applicant: 'Uniq Creation Pte. Ltd.',
    status: 'Registered',
    notes: 'EU-wide community design registration protecting the curved edge bezel geometry with integrated air-cushion pockets.',
    documentName: 'euipo_design_clarion.pdf',
    documentType: 'application/pdf',
    documentSize: '1.8 MB',
    createdAt: '2022-01-14T09:20:00Z',
    updatedAt: '2022-03-01T15:10:00Z',
  },
  {
    id: 'IPA-1008',
    assetName: 'UNIQ Venture Travel Organizer Casing',
    ipType: 'Design',
    brand: 'UNIQ',
    applicationNumber: 'AU-DES-202114299',
    country: 'Australia',
    countryCode: 'AU',
    filingDate: '2021-05-19',
    classes: 'Locarno: 03-01',
    registrationNumber: '202114299',
    registrationDate: '2021-08-14',
    renewalDueDate: '2026-05-19',
    firmAgent: 'Davies Collison Cave',
    applicant: 'Uniq Creation Pte. Ltd.',
    status: 'Abandoned',
    notes: 'Decision made by IP steering committee not to proceed with Stage 2 examination following commercial product line sunset.',
    documentName: 'au_abandonment_notification.pdf',
    documentType: 'application/pdf',
    documentSize: '410 KB',
    createdAt: '2021-05-19T07:10:00Z',
    updatedAt: '2026-05-20T10:00:00Z',
  },
  {
    id: 'IPA-1009',
    assetName: 'SKINARMA Haptic Armband Mechanism',
    ipType: 'Patent',
    brand: 'Skinarma',
    applicationNumber: 'US-PAT-2024-009182',
    country: 'United States',
    countryCode: 'US',
    filingDate: '2024-01-09',
    classes: 'IPC: A44C 5/00, G04G 17/08',
    registrationNumber: '-',
    registrationDate: '-',
    renewalDueDate: '2028-01-09',
    firmAgent: 'Finnegan, Henderson & Farabow',
    applicant: 'Skinarma Holdings Ltd.',
    status: 'To Be Filed',
    notes: 'Magnetic modular docking hinge with quick-release security lock for smartwatch band integration. Specification drafting in progress.',
    documentName: 'uspto_provisional_haptic.pdf',
    documentType: 'application/pdf',
    documentSize: '1.2 MB',
    createdAt: '2024-01-09T14:00:00Z',
    updatedAt: '2024-06-18T11:45:00Z',
  },
  {
    id: 'IPA-1010',
    assetName: 'ENERGEA AmpVolt GaN Ultra-Compact Architecture',
    ipType: 'Patent',
    brand: 'Energea',
    applicationNumber: 'MY-PAT-PI2023004819',
    country: 'Malaysia',
    countryCode: 'MY',
    filingDate: '2023-09-12',
    classes: 'IPC: H01F 27/28, H02M 3/335',
    registrationNumber: 'MY-194821-A',
    registrationDate: '2024-02-28',
    renewalDueDate: '2027-09-12',
    firmAgent: 'Shearn Delamore & Co.',
    applicant: 'Energea Tech Pte. Ltd.',
    status: 'Registered',
    notes: 'Planar transformer circuitry with stacked Gallium Nitride power stages enabling 67W power delivery in miniature footprint.',
    documentName: 'myipo_patent_grant_gan.pdf',
    documentType: 'application/pdf',
    documentSize: '2.8 MB',
    createdAt: '2023-09-12T03:30:00Z',
    updatedAt: '2024-01-15T08:00:00Z',
  },
];

export const BRAND_DEFAULT_MAPS: Record<string, { registered: string[]; pending: string[] }> = {
  UNIQ: {
    registered: ['SG', 'US', 'DE', 'FR', 'GB', 'JP', 'AU', 'CA', 'IT', 'ES'],
    pending: ['IN', 'BR', 'MX', 'ID', 'TH', 'VN'],
  },
  Skinarma: {
    registered: ['JP', 'KR', 'SG', 'US', 'GB', 'TW', 'TH'],
    pending: ['AU', 'DE', 'AE', 'CN', 'PH'],
  },
  Energea: {
    registered: ['SG', 'MY', 'GB', 'ID', 'TH', 'VN', 'PH'],
    pending: ['US', 'CN', 'JP', 'DE', 'AU', 'IN'],
  },
};

export const COUNTRY_OPTIONS = [
  { name: 'United States', code: 'US' },
  { name: 'Singapore', code: 'SG' },
  { name: 'Japan', code: 'JP' },
  { name: 'China', code: 'CN' },
  { name: 'United Kingdom', code: 'GB' },
  { name: 'Germany', code: 'DE' },
  { name: 'South Korea', code: 'KR' },
  { name: 'Australia', code: 'AU' },
  { name: 'Canada', code: 'CA' },
  { name: 'France', code: 'FR' },
  { name: 'Italy', code: 'IT' },
  { name: 'Spain', code: 'ES' },
  { name: 'Malaysia', code: 'MY' },
  { name: 'Indonesia', code: 'ID' },
  { name: 'Thailand', code: 'TH' },
  { name: 'Vietnam', code: 'VN' },
  { name: 'Philippines', code: 'PH' },
  { name: 'India', code: 'IN' },
  { name: 'Brazil', code: 'BR' },
  { name: 'Mexico', code: 'MX' },
  { name: 'United Arab Emirates', code: 'AE' },
  { name: 'Taiwan', code: 'TW' },
];
